const notes = {
  A4: new Audio("/piano-mp3/A4.mp3"),
  A5: new Audio("/piano-mp3/A5.mp3"),
  Ab4: new Audio("/piano-mp3/Ab4.mp3"),
  Ab5: new Audio("/piano-mp3/Ab5.mp3"),
  B4: new Audio("/piano-mp3/B4.mp3"),
  B5: new Audio("/piano-mp3/B5.mp3"),
  Bb4: new Audio("/piano-mp3/Bb4.mp3"),
  Bb5: new Audio("/piano-mp3/Bb5.mp3"),
  C4: new Audio("/piano-mp3/C4.mp3"),
  C5: new Audio("/piano-mp3/C5.mp3"),
  D4: new Audio("/piano-mp3/D4.mp3"),
  D5: new Audio("/piano-mp3/D5.mp3"),
  Db4: new Audio("/piano-mp3/Db4.mp3"),
  Db5: new Audio("/piano-mp3/Db5.mp3"),
  E4: new Audio("/piano-mp3/E4.mp3"),
  E5: new Audio("/piano-mp3/E5.mp3"),
  Eb4: new Audio("/piano-mp3/Eb4.mp3"),
  Eb5: new Audio("/piano-mp3/Eb5.mp3"),
  F4: new Audio("/piano-mp3/F4.mp3"),
  F5: new Audio("/piano-mp3/F5.mp3"),
  G4: new Audio("/piano-mp3/G4.mp3"),
  G5: new Audio("/piano-mp3/G5.mp3"),
  Gb4: new Audio("/piano-mp3/Gb4.mp3"),
  Gb5: new Audio("/piano-mp3/Gb5.mp3"),
};

export default notes;
